services:
  # Servicio de la aplicación Django
  web:
    build: .
    container_name: myproject_web
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - myprojectnet
    restart: unless-stopped

  # Base de datos PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_app_citas
    environment:
      POSTGRES_DB: ${DB_NAME:-app_citas}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-14251425}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myprojectnet
    restart: unless-stopped

  # pgAdmin para administrar PostgreSQL (opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
    - pgadmin_data:/var/lib/pgadmin 
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - myprojectnet
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: 

networks:
  myprojectnet:
    driver: bridge