# Generated by Django 5.0.8 on 2025-05-02 00:31

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50, unique=True)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EC', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('descripcion', models.TextField(max_length=50)),
                ('servicio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, max_length=50, null=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresas')),
            ],
        ),
    ]
