# Generated by Django 5.0.8 on 2025-05-02 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_empresas_citas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='empresa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empresas'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='notas',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='citas',
            name='usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
