# Generated by Django 5.0.8 on 2025-05-15 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_empresas_direccion_alter_empresas_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='empresa_id',
            new_name='empresa',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='citas',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
            preserve_default=False,
        ),
    ]
