# Generated by Django 5.0.8 on 2025-05-20 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_empresa_id_citas_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
