# Generated by Django 5.0.8 on 2025-06-15 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_empresas_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atenciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atnecion', models.DateField(unique=True)),
                ('notas', models.TextField(blank=True, max_length=100, null=True)),
                ('cita_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.citas')),
            ],
        ),
    ]
