# Generated by Django 5.0.8 on 2025-06-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_atenciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atenciones',
            name='notas',
        ),
    ]
