# Generated by Django 5.0.8 on 2025-06-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_atenciones_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atenciones',
            old_name='cita_id',
            new_name='cita',
        ),
    ]
