# Generated by Django 5.0.8 on 2025-06-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_cita_id_atenciones_cita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atenciones',
            old_name='fecha_atnecion',
            new_name='fecha_atencion',
        ),
    ]
