# Generated by Django 5.0.8 on 2025-06-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_fecha_atnecion_atenciones_fecha_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atenciones',
            name='fecha_atencion',
            field=models.DateField(),
        ),
    ]
