# Generated by Django 5.0.8 on 2025-07-07 22:09

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_atenciones_fecha_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
