# Generated by Django 5.0.8 on 2025-07-16 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_empresas_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='atenciones',
            name='empresas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empresas'),
        ),
    ]
