# Generated by Django 5.0.8 on 2025-07-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_atenciones_empresas'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
