# Generated by Django 5.0.8 on 2025-07-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userprofile_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
